// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalHeindall.Data;

#nullable disable

namespace AppHeindall.Migrations
{
    [DbContext(typeof(GrupoContext))]
    [Migration("20230315133938_Alteracao-Metas")]
    partial class AlteracaoMetas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AppHeindall.Models.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Demanda")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("Finish")
                        .HasColumnType("Date");

                    b.Property<string>("Pendencia")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Prioridade")
                        .HasColumnType("longtext");

                    b.Property<string>("Projeto")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Start")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.ToTable("Meta");
                });

            modelBuilder.Entity("IntegradorUsuario", b =>
                {
                    b.Property<int>("IntegradoresId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.HasKey("IntegradoresId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("IntegradorUsuario");
                });

            modelBuilder.Entity("PortalHeindall.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GrupoArea")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("GrupoMetodo")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoName")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoPassword")
                        .HasColumnType("longtext");

                    b.Property<int>("GrupoPort")
                        .HasColumnType("int");

                    b.Property<string>("GrupoType")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoURL")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoUser")
                        .HasColumnType("longtext");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("longtext");

                    b.Property<string>("PublicKey")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("PortalHeindall.Models.Integrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("GrupoPassword")
                        .HasColumnType("longtext");

                    b.Property<int>("GrupoPort")
                        .HasColumnType("int");

                    b.Property<string>("GrupoUser")
                        .HasColumnType("longtext");

                    b.Property<int>("IntegradorId")
                        .HasColumnType("int");

                    b.Property<string>("IntegradorNome")
                        .HasColumnType("longtext");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("longtext");

                    b.Property<string>("PublicKey")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("Integradores");
                });

            modelBuilder.Entity("PortalHeindall.Models.IntegradordoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IntegradorId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IntegradorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("IntegradoresdoUsuario");
                });

            modelBuilder.Entity("PortalHeindall.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UsuarioBancoDestino")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioCNPJ")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioIDAgencia")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioName")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioNivel")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("IntegradorUsuario", b =>
                {
                    b.HasOne("PortalHeindall.Models.Integrador", null)
                        .WithMany()
                        .HasForeignKey("IntegradoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalHeindall.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalHeindall.Models.Integrador", b =>
                {
                    b.HasOne("PortalHeindall.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PortalHeindall.Models.IntegradordoUsuario", b =>
                {
                    b.HasOne("PortalHeindall.Models.Integrador", "Integrador")
                        .WithMany()
                        .HasForeignKey("IntegradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalHeindall.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integrador");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
